[ai]
max_tokens = 4096
overview_max_tokens = 4096
explain_max_tokens = 8192
test_max_tokens = 2048
temperature = 0.0
repeat_penalty = 1.15
selected_model = "Llama-3.2-3B-Instruct-Q4_K_M.gguf"

[repo]
max_download_size_mb = 300
