[ai]
max_tokens = 1024
overview_max_tokens = 1024
explain_max_tokens = 1024
test_max_tokens = 1024
temperature = 0.0
repeat_penalty = 1.15
selected_model = "tinyllama-1.1b-chat-v1.0.Q4_K_S.gguf"

[repo]
max_download_size_mb = 300
